config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'static_pages#home'
  get  '/help',           to: 'static_pages#help'
  get  '/about',          to: 'static_pages#about'
  get  '/contact',        to: 'static_pages#contact'
  get  '/signup',         to: 'users#new'
  post '/signup',         to: 'users#create'
  get  '/login',          to: 'sessions#new'
  post '/login',          to: 'sessions#create'
  delete '/logout',       to: 'sessions#destroy'
  get  '/createQuiz',     to: 'quizzes#new'
  post '/createQuiz',     to: 'quizzes#create'
  get  '/listQuiz',       to: 'quizzes#list'
  get  '/createQuestion', to: 'questions#new'
  post '/createQuestion', to: 'question#create'
  get  '/createAnswer',   to: 'answer#new'
  post '/createAnswer',   to: 'answer#create'
  get  '/takeQuiz',       to: 'quizzes#take'
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :quizzes
  resources :questions
  resources :answers
  
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :quiz
  has_many :answers, dependent: :destroy
  validates :title, presence: :true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end
  
  def new
    @question = Question.new
  end
  
  def create
    @question = Quiz.first.questions.build(question_params)
    if @question.save
      redirect_to new_answer_url
    else
      render static_pages/home
    end
  end  
  
  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_questions.html.erb
<li id="question-<%= question.id %>">
  <%= link_to gravatar_for(Quiz.find(question.quiz_id), size: 50), Quiz.find(question.quiz_id) %>
  <span class="title"><%= question.title %></span>
</li>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Quiz</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.title %></td>
        <td><%= quiz.user_id %></td>
        <td><%= link_to 'Show', question %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<% provide(:title, 'New Questions') %>
<h1>New Questions</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@question) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :title%>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.submit "Submit the Question", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @question.title %>
</p>

<p>
  <strong>Quiz:</strong>
  <%= @question.quiz_id %>
</p>

<%= link_to 'Back', questions_path %>