config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'static_pages#home'
  get  '/help',           to: 'static_pages#help'
  get  '/about',          to: 'static_pages#about'
  get  '/contact',        to: 'static_pages#contact'
  get  '/signup',         to: 'users#new'
  post '/signup',         to: 'users#create'
  get  '/login',          to: 'sessions#new'
  post '/login',          to: 'sessions#create'
  delete '/logout',       to: 'sessions#destroy'
  get  '/createQuiz',     to: 'quizzes#new'
  post '/createQuiz',     to: 'quizzes#create'
  get  '/listQuiz',       to: 'quizzes#list'
  get  '/createQuestion', to: 'questions#new'
  post '/createQuestion', to: 'question#create'
  get  '/createAnswer',   to: 'answer#new'
  post '/createAnswer',   to: 'answer#create'
  get  '/takeQuiz',       to: 'quizzes#take'
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :quizzes
  resources :questions
  resources :answers
  
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :user
  has_many :questions, dependent: :destroy
  has_many :scores, dependent: :destroy
  validates :title, presence: :true
  
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  def index
    @quizzes = Quiz.all
  end
  
  def new
    @quiz = Quiz.new
  end
  
  def create
    @quiz = current_user.quizzes.build(quiz_params)
    if @quiz.save
      redirect_to createQuestion_url
    else
      render static_pages/home
    end
  end  
      
  
  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def quiz_params
      params.require(:quiz).permit(:title)
    end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/_form.html.erb
<%= form_for(quiz) do |f| %>
  <% if quiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
      <% quiz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_area :title %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :question_ids %>
    <%= f.number_field :question_ids %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quizzes/_quiz.html.erb
<li id="quiz-<%= quiz.id %>">
  <%= link_to gravatar_for(User.find(quiz.user_id), size: 50), User.find(quiz.user_id) %>
  <span class="user"><%= link_to User.find(quiz.user_id).name, User.find(quiz.user_id) %></span>
  <span class="title"><%= quiz.title %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(quiz.created_at) %> ago.
    <%= link_to "Take", takeQuiz_path %>
  </span>
</li>

app/views/quizzes/_quizzes.html.erb
<li id="quiz-<%= quiz.id %>">
  <%= link_to gravatar_for(User.find(quiz.user_id), size: 50), User.find(quiz.user_id) %>
  <span class="user"><%= link_to User.find(quiz.user_id).name, User.find(quiz.user_id) %></span>
  <span class="title"><%= quiz.title %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(quiz.created_at) %> ago.
    <% if current_user == User.find(quiz.user_id) %>
      <%= link_to "delete", quiz, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>

  </span>
</li>

app/views/quizzes/edit.html.erb
<h1>Editing Quiz</h1>

<%= render 'form', quiz: @quiz %>

<%= link_to 'Show', @quiz %> |
<%= link_to 'Back', quizzes_path %>

app/views/quizzes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quizzes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quizzes.each do |quiz| %>
      <tr>
        <td><%= quiz.title %></td>
        <td><%= quiz.user_id %></td>
        <td><%= link_to 'Show', quiz %></td>
        <td><%= link_to 'Edit', edit_quiz_path(quiz) %></td>
        <td><%= link_to 'Destroy', quiz, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quiz', new_quiz_path %>

app/views/quizzes/list.html.erb
<div class="col-md-8">
    <% @quizzes = Quiz.all %>
      <h3>Quizzes</h3>
      <ol class="quizzes">
        <%= render @quizzes %>
      </ol>

app/views/quizzes/new.html.erb
<% provide(:title, 'New Quiz') %>
<h1>New Quiz</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@quiz) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :title%>
      <%= f.text_field :title, class: 'form-control' %>
        
      <%= f.submit "Create the Quiz", class: "btn btn-primary" %>    
    <% end %>
  </div>
</div>

app/views/quizzes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @quiz.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @quiz.user_id %>
</p>

<%= link_to 'Back', quizzes_path %>

app/views/quizzes/take.html.erb
<h1>Good Luck!</h1>

<%= @quiz = Quiz.reorder('created_at asc').first %>
<%= @question = Question.find(@quiz.id) %>
<%= @answer = Answer.find(@question.id)  %>


<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @quiz.title %>
      </h1>
    </section>
  </aside>
</div>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @question.title %>
      </h1>
    </section>
  </aside>
</div>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= link_to @answer.content, root_path, class: "btn btn-lg btn-primary" %>
      </h1>
    </section>
  </aside>
</div>