config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'static_pages#home'
  get  '/help',           to: 'static_pages#help'
  get  '/about',          to: 'static_pages#about'
  get  '/contact',        to: 'static_pages#contact'
  get  '/signup',         to: 'users#new'
  post '/signup',         to: 'users#create'
  get  '/login',          to: 'sessions#new'
  post '/login',          to: 'sessions#create'
  delete '/logout',       to: 'sessions#destroy'
  get  '/createQuiz',     to: 'quizzes#new'
  post '/createQuiz',     to: 'quizzes#create'
  get  '/listQuiz',       to: 'quizzes#list'
  get  '/createQuestion', to: 'questions#new'
  post '/createQuestion', to: 'question#create'
  get  '/createAnswer',   to: 'answer#new'
  post '/createAnswer',   to: 'answer#create'
  get  '/takeQuiz',       to: 'quizzes#take'
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :quizzes
  resources :questions
  resources :answers
  
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  validates :content, presence: :true
  
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
    @answers = Answer.all
  end
  
  def new
    @answer = Answer.new
  end
  
  def show
    @answer = Answer.find(params[:id])
  end
  
  def create
    @answer = Question.first.answers.build(answer_params)
    if @answer.save
      redirect_to root_url
    else
      render static_pages/home
    end
  end  
  
  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:content, :correct)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answers.html.erb
<li id="answer-<%= answer.id %>">
  <%= link_to gravatar_for(answer.question, size: 50), answer.question %>
  <span class="content"><%= answer.content %></span>
</li>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Answers</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Correct</th>
      <th>Question</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.content %></td>
        <td><%= answer.correct %></td>
        <td><%= answer.question_id %></td>
        <td><%= link_to 'Show', answer %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<% provide(:title, 'New Answers') %>
<h1>New Answers</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@answer) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :content%>
      <%= f.text_field :content, class: 'form-control' %>
      
      <%= f.label :correct%>
      <input type="checkbox" name="Correct?" value="Correct?" checked> This answer is correct<br>    
      <%= f.submit "Submit the Answer", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @answer.content %>
</p>

<p>
  <strong>Question</strong>
  <%= @answer.question_id %>
</p>

<p>
  <strong>Correct</strong>
  <%= @answer.correct %>
</p>

<%= link_to 'Back', answers_path %>